Refactoring Siddhi GPL GEO extension
wso2-extensions/siddhi-gpl-execution-geo pull request #5
Opened 2017-06-19 09:07 UTC by AnuGayan

2017-06-19 09:33 UTC, AnuGayan reviewed
Please review and merge

2017-06-19 12:25 UTC, suhothayan requested changes

2017-06-19 12:25 UTC, suhothayan commented on component/pom.xml
> +        <version>4.0.0</version>
it should be 4.0.0-SNAPSHOT

2017-06-19 12:25 UTC, suhothayan commented on component/pom.xml
> +    <name>Siddhi Execution Extension - Geo</name>
Siddhi "GPL" Execution Extension - Geo  missed GPL

2017-06-19 12:25 UTC, suhothayan commented on component/pom.xml
> +            <version>6.8</version>
Move version to properties

2017-06-19 12:25 UTC, suhothayan commented on feature/pom.xml
> +    <description>This feature contains Siddhi extension feature for Geo.kk</description>
feature should be deleted

2017-06-19 12:25 UTC, suhothayan commented on pom.xml
> +        <junit.version>4.12</junit.version>
remove junit, use testng

2017-06-19 12:25 UTC, suhothayan commented on pom.xml
> +                <version>6.8</version>
move version to properties

2017-06-19 12:25 UTC, suhothayan commented on component/pom.xml
> +        <version>4.0.0</version>
Component artifactId should not have "-parent" part in the name componet.

2017-06-20 04:05 UTC, AnuGayan commented on component/pom.xml
> +        <version>4.0.0</version>
@suhothayan Fixed the version.  
"-parent" in the artifactId is just to refer to the parent pom.

2017-06-20 04:06 UTC, AnuGayan commented on component/pom.xml
> +    <name>Siddhi Execution Extension - Geo</name>
@suhothayan Fixed

2017-06-20 04:06 UTC, AnuGayan commented on component/pom.xml
> +            <version>6.8</version>
@suhothayan Fixed

2017-06-20 04:06 UTC, AnuGayan commented on feature/pom.xml
> +    <description>This feature contains Siddhi extension feature for Geo.kk</description>
@suhothayan Fixed

2017-06-20 04:09 UTC, AnuGayan commented on pom.xml
> +        <junit.version>4.12</junit.version>
@suhothayan Fixed

2017-06-20 04:09 UTC, AnuGayan commented on pom.xml
> +                <version>6.8</version>
@suhothayan Fixed

2017-06-20 11:21 UTC, tishan89 requested changes

2017-06-20 11:21 UTC, tishan89 commented on component/pom.xml
> +        <version>4.0.0-SNAPSHOT</version>
make it 1.0.0 snapshot

2017-06-20 11:21 UTC, tishan89 commented on feature/pom.xml
>  -->
remove feature all together

2017-06-20 11:21 UTC, tishan89 commented on pom.xml
> +    <version>4.0.0-SNAPSHOT</version>
1.0.0-SNAPSHOT

2017-06-20 12:30 UTC, AnuGayan commented on feature/pom.xml
>  -->
@tishan89 Done

2017-06-20 12:32 UTC, tishan89 approved these changes

2017-06-20 14:02 UTC, merged